### ISSUE TITLE
Demo scene and CardboardControlManager prefab are blank when imported to Unity 4.6

### ISSUE THREAD

**Issue by jonomf** [JScott/cardboard-controls#10]
Installing this library through the UnityPackage into Unity 4.6.0f2, the ControlsDemo scene appears empty, and the CardboardControlManager prefab appears as an unrecognized object in the project, and cannot be used as a prefab.  
Importing the same package into Unity 5 works fine. 
Thanks!
![cardboardcontrolsunity460blankfiles](https://cloud.githubusercontent.com/assets/539728/7955483/a2a4780e-09a6-11e5-8df8-5da1ad442d6c.PNG)

**Comment by JScott** [comment]
Yeah, the last version I tested on Unity 4.6 was [v2.2](https://github.com/JScott/cardboard-controls/releases/tag/v2.2). It's old enough that it's still using Durovis Dive and feels like a very different product than the latest stuff.

What's your use case for using older Unity? I never bothered supporting it because Unity was making such a big push for 5.0 and I have no metrics on who wants to stay with 4.6 for whatever reason.

**Comment by jonomf** [comment]
In my case, some other plugins I'm using in my project are not yet compatible with Unity 5.  I also don't have any metrics on how many people are still on 4.x, so take it with a grain of salt (I'll happily upgrade to 5 one of these days!).

**Comment by JScott** [comment]
I'm hesitant to actively support 4.x because Google's Cardboard SDK for Unity [has a bug](https://developers.google.com/cardboard/unity/release-notes#known_issues_4) in Unity 4.x that prevents various sensor data from being read, which prevents core functionality of Cardboard Controls+. I would have to go back to depending on Durovis Dive which has a restrictive license that complicates things for both of us and would alter your end product.

If you want to try v2.2, the [files are all there](https://github.com/JScott/cardboard-controls/tree/6098d9cf1eff9ce79b2d84fad7531719b10f3d32). I'd be supportive if you wanted to contribute to keeping things up-to-date for older environments but right now it doesn't make sense for me to do it.

I wish I had a better answer for you :( I guess at least it's a good incentive to put pressure on the creators of those other plugins to update. It's way easier to go forward than back.

**Comment by JScott** [comment]
And by "supportive" I mean that I could actually lend guidance and experience since this was using Dive before and I know what would need to change. Not just a moral support sort of thing, to be clear.
