### ISSUE TITLE
Magnetic Events don't work

### ISSUE THREAD

**Issue by PhilipSieberg** [JScott/cardboard-controls#12]
I'm using a Nexus 5, and for me none of the Magnetic Inputs work.
If i put my Device in my Cardboard the Magnetic States don't work and the Click event doesn't recognize Clicks.
However if i open the Cardboard and move my Device closer and or away from the Device i get some kind of Input.

I would love to use this for a little game and won't mind to pay fpr the Unity Package if it works.
I would be glad if you could help me fix this problem.

**Comment by harschell** [comment]
Well remove that magnet and use some copper tap touch input for time being
or you can consider using wireless mouse as input device connect it using
USB OTG. or use any Bluetooth controller there are many on Internet buy the
one you like.
If you still wants to persist with magnetic thing put that magnet to other
side of cardboard. But this will show upside down view.
Well right now I'm facing some health issues, may be tomorrow I'll be able
to get back to you with some more information.

**Comment by PhilipSieberg** [comment]
I really would like to use the Magnet as an Input.
Thanks for the quick answer, for the time i'll use your suggestion and use a copper wire

**Comment by JScott** [comment]
I would also like your magnet to work. Have you used some of the debug charts or Unity sensor variables to see what the readings are? Should I also assume that other Cardboard applications run fine and it's just CC+ that's behaving out of the ordinary?

Unfortunately, the best solution to magnet problems is often to rely on the touch screen instead, like Cardboard v2 does. I'm going to build that in to the framework soon, for what it's worth. Interested in hearing what you other info you have @harschell since it sounds like you're on that same path.

**Comment by PhilipSieberg** [comment]
I tried some of the featured Cardboard Apps and they worked fine.
I dont quite understand how this magnet thing works, i know my device can track magnetic fields (it can work as a compass so i guess thats it) i looked at your code (very nice naming and very readable, really appreciate that) and i mostly understand it, but not enough to fix it myself.
My guess is that something with the intensity of the magnetic field change isnt right. i can simulate clicks and up/down states by moving my device around the magnet of my cardboard.

"Have you used some of the debug charts or Unity sensor variables to see what the readings are?"
I think that might solve my problem, but i'm not very experienced working with unity so i'm not sure how to do this.

**Comment by JScott** [comment]
Awesome, we can work with that. I'll give you a bit more guidance here
later tonight to help figure it out.

**Comment by JScott** [comment]
First, the magnetometer measures the vector of the magnetic field around your device. This is used to calculate the compass stuff but it's just a 3D vector. The ParsedSensorData class deals with measuring the change in that vector as the magnet moves.

Unfortunately, a lot of the magic numbers in there just came from me tweaking it  and paying attention to the values. That's always what I assume breaks things for people. For all I know, my numbers only work in my geographic region because of the variation in Earth's magnetic field.

---

For the charts, go to the CardboardControlManager prefab and enable debug charts in the Inspector under the CardboardControl script. You'll need to use `.../android-sdk/platform-tools/adb logcat` to actually read the output from your device. This should tell you at least what state the sensor thinks it should be in to make sure there's no anomalies there.

If it's what you expect in the charts then we may have to get to metal and just output `Input.compass.rawVector.magnitude` to the log and see how it changes. For example, if it's constant or 0, you know something's up. Again, you'll have to use `adb logcat` to actually read the output live from your device.

Short of screen sharing there's not much I can do to debug your device. Hopefully that clears things up but let me know if something needs better explaining.

**Comment by JScott** [comment]
And now you know why I'm so jazzed about the new Cardboard design where it's just a screen tap instead of this magnet vector stuff.

**Comment by PhilipSieberg** [comment]
thanks a lot for all your help and work
You're a good guy!!!
I'll try my best to get it to work !

**Comment by JScott** [comment]
Let me know how it goes or if I can help with anything. It's a difficult problem for sure.

**Comment by harschell** [comment]
@PhilipSieberg  I had a similar problem with my LG g3, the trigger wasn't doing anything. I turned the magnets the other way around ( have black one outside and the silver one inside) and for some strange reason that worked. Let me know if this works for you :)

**Comment by JScott** [comment]
I was doing the update to support Cardboard v2 when I realized that I was working against a really old version of the Cardboard SDK, I think v0.4.5. When I updated it broke magnetic events as well so maybe try grabbing [the older version](https://github.com/googlesamples/cardboard-unity/releases/tag/v0.4.5)? At least until I get it worked with v0.5.1.

**Comment by JScott** [comment]
Just got the latest bits working in [v3.2](https://github.com/JScott/cardboard-controls/releases/tag/v3.2), which includes the version of Cardboard SDK I tested against. Give it a shot and let me know if the problem persists.

**Comment by PhilipSieberg** [comment]
thanks a lot man, for me its late in the evening i will test it tomorrow and let you know if it works or not :)

**Comment by PhilipSieberg** [comment]
your new version fixed the magnetic events for me ! really nice

sadly 90% of the time i do a click it rotates my screen so the demo app is upside down or sideways
and everytime i do a click it moves the screen like i rotate my head but i don't actually do it

and when i hold the trigger the screen rotates a little like i slowly turn my head right.

any idea how to fix this ?

**Comment by JScott** [comment]
Well that's weird! I know the sensors can take a little time to calibrate and sometimes drift but nothing I call would explicitly change the orientation.

Anyway, since the original issue was fixed by the update I'm going to close the issue. Please feel free to open another one if the other problems persist.
