### ISSUE TITLE
Scripts Unlinked from Prefabs - Script Cannot Be Loaded

### ISSUE THREAD

**Issue by BodaciousMike** [JScott/cardboard-controls#21]
For some reason whenever I import the files all of the scripts are removed from the prefabs.

**Comment by HAZARDU5** [comment]
You'll want to make sure you import the Unity package in the [latest release](https://github.com/JScott/cardboard-controls/releases/latest). That way it will ensure all the script linkages come through into your project correctly.

**Comment by JScott** [comment]
If there's still issues after that, try deleting all the files and re-importing them. Sometimes Unity packages do weird things when files get moved around from version to version.

I'm going to close this for now because I just uploaded v3.6.1 and I tested it on a blank project to make sure everything worked as expected. @BodaciousMike, let me know if you're still having issues but I assume you worked it out since you haven't responded in a few days.
