### ISSUE TITLE
Cannot build from demo scene

### ISSUE THREAD

**Issue by dotlaura** [JScott/cardboard-controls#26]
Unity 5.6.2f1, latest CardboardControls+ from GitHub.

I am doing the following:

- Creating new project
- Change  platform to Android
- Import CardboardControls+ from package
- (tried this with/without) Commenting out  based on alert to remove mentions of cardboard from Android Manifest
- Enable virtual reality in player settings, add Cardboard to the list
- Opening the demo scene
- Build

Playing scene in Unity works, but building to Android always leads to instant force-close on phone. Can run GVR fine on phone.

**Comment by JScott** [comment]
That doesn't sound very fun! I'm on vacation right now but I want to check it out later. If you can package up your crashing project and share it then it'll be a lot easier to properly diagnose.

**Comment by dotlaura** [comment]
Thanks, that would be great! I've literally imported and packaged, then I zipped the project file if that's also helpful. 

https://www.dropbox.com/s/6gf1whb4vbobsf5/CardboardControlsImported.zip?dl=0
https://www.dropbox.com/s/giag1m2sqs49hez/FinalCardboardControlsProject.zip?dl=0

**Comment by JScott** [comment]
@dotlaura Exactly what I needed, thanks :) I also forgot to ask: what phone model are you running it on that it crashes? The version of GVR that CC+ targets is kind of old now so that could be a piece of the puzzle. I'll be making some time this week to dive into it.

**Comment by JScott** [comment]
Okay, so first thanks for your patience. I found this in the logs:

```
E/AndroidRuntime(22144): FATAL EXCEPTION: main
E/AndroidRuntime(22144): Process: com.WSP.FinalCardboardControls, PID: 22144
E/AndroidRuntime(22144): java.lang.RuntimeException: Unable to instantiate activity ComponentInfo{com.WSP.FinalCardboardControls/com.google.unity.GoogleUnityActivity}: java.lang.ClassNotFoundException: Didn't find class "com.google.unity.GoogleUnityActivity" on path: Dex
PathList[[zip file "/data/app/com.WSP.FinalCardboardControls-1/base.apk"],nativeLibraryDirectories=[/data/app/com.WSP.FinalCardboardControls-1/lib/arm, /vendor/lib, /system/lib]]
E/AndroidRuntime(22144):        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2993)
E/AndroidRuntime(22144):        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3248)
E/AndroidRuntime(22144):        at android.app.ActivityThread.access$1000(ActivityThread.java:197)
E/AndroidRuntime(22144):        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1681)
E/AndroidRuntime(22144):        at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime(22144):        at android.os.Looper.loop(Looper.java:145)
E/AndroidRuntime(22144):        at android.app.ActivityThread.main(ActivityThread.java:6872)
E/AndroidRuntime(22144):        at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(22144):        at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime(22144):        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
E/AndroidRuntime(22144):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)
E/AndroidRuntime(22144): Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.unity.GoogleUnityActivity" on path: DexPathList[[zip file "/data/app/com.WSP.FinalCardboardControls-1/base.apk"],nativeLibraryDirectories=[/data/app/com.WSP.FinalCardboard
Controls-1/lib/arm, /vendor/lib, /system/lib]]
E/AndroidRuntime(22144):        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
E/AndroidRuntime(22144):        at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
E/AndroidRuntime(22144):        at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
E/AndroidRuntime(22144):        at android.app.Instrumentation.newActivity(Instrumentation.java:1080)
E/AndroidRuntime(22144):        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2983)
E/AndroidRuntime(22144):        ... 10 more
E/AndroidRuntime(22144):        Suppressed: java.lang.ClassNotFoundException: com.google.unity.GoogleUnityActivity
E/AndroidRuntime(22144):                at java.lang.Class.classForName(Native Method)
E/AndroidRuntime(22144):                at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
E/AndroidRuntime(22144):                at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
E/AndroidRuntime(22144):                at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
E/AndroidRuntime(22144):                ... 13 more
E/AndroidRuntime(22144):        Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available
W/ActivityManager( 1142):   Force finishing activity 1 com.WSP.FinalCardboardControls/com.google.unity.GoogleUnityActivity
```

It has something to do with the manifests in the Plugin directory: https://stackoverflow.com/questions/39655627/android-didnt-find-class-com-google-unity-googleunityactivity

I got it compiling by deleting the Plugins directory and replacing it with the one from the newest version of GVR from GitHub. However, the gaze was off by a lot. The color changing cube was on the right side of the screen before it started registering that it was in the middle of the screen. I'm not sure why suddenly it's not working when it did before so you could also try older builds of CC+.

Here's the project thus far, with ct2.apk as the compiled project that doesn't crash: https://www.dropbox.com/s/xberue7ag5eo22a/FinalCardboardControls%20redux.zip?dl=0


So that's not a very good answer but it's a start. I think the real solution is updating to support a newer version of GVR. GVR 1.5 changed a lot and we're up to 1.6 now so it'll take a while to see if I can get it working or fall back to 1.4 if I can't. I'm game to support you if you need it quickly and want to try the update yourself as well :)

**Comment by dotlaura** [comment]
Hello, thanks for this. I'm happy to keep playing around while it's being updated - I don't have a specific project and deadline at the moment for a cardboard app but I do want to learn CC+.

I'm using it on an LG G5 if that still helps- let me know if you want a tester!

**Comment by JScott** [comment]
Basically all that needs to be done is delete `GoogleVR` and `Plugins` directories, replace them with the newest stuff, and then fix all the numerous errors that will result. I'm probably going to just start at [the release notes for v1.30](https://developers.google.com/vr/unity/release-notes#google_vr_sdk_for_unity_v130) and make my way up to see all the things that changed because it's enough that guessing just led to more problems when I tried v1.5. Feel free to ask me any questions if you want to play around with it on your own. Not everyone is comfortable blasting questions on a public forum so you can can also reach me at the email in my profile. Either way I'll post here when I've made some progress.

Also, looking at the notes for 1.4 it seems that they have up/down/held for `GvrController` but I'm not sure what that means for Cardboard vs. Daydream and also it's still just a bunch of booleans instead of C# Delegates. Someone tell me if CC+ ever becomes obsolete so I'm not upgrading it for no reason :P

**Comment by JScott** [comment]
I got it working on GVR 1.60 and committed the code to master. It's all generally the same but I added a Player prefab and added some things to the existing manager prefab because Google made the system more complicated. I have to do some code cleanup before I push a new release out though.

**Comment by dotlaura** [comment]
That's great, thank you. Can confirm it's working well on my LG G5!

I'll definitely post if I have more questions.

**Comment by JScott** [comment]
Excellent! You're very welcome and thanks for taking the time to bring up the issue. Good luck in your GVR journey :)
