### ISSUE TITLE
Missing Scripts/prefabs

### ISSUE THREAD

**Issue by kharysiri** [JScott/cardboard-controls#5]
Hi, im trying this plugin in Unity 5.0.1f1 (32-bit), when i load the demo scene, there are a missing prefab, i was thinking that CardboardControlManager was the missing one, but when i load that prefab, all of his scripts are missing (also bigcube and ExampleCharacter has missing scripts), any ideas?
![prtscr capture_2](https://cloud.githubusercontent.com/assets/4591541/7707690/1394415e-fe1f-11e4-999a-fb942f111b1e.jpg)

**Comment by JScott** [comment]
My guess is that I moved scripts around and forgot to update the prefab. Those scripts should point to:
- CardboardControl.cs
- CardboardControlMagnet.cs
- CardboardControlGaze.cs
- CardboardControlBox.cs

Let me know if redirecting them fixes it. Otherwise I'll check it out myself when I get some time and update the repo.

**Comment by kharysiri** [comment]
Hi! ty for aswering quickly!
I tried to redirect the scripts but, still doesnt work for me =S
well ill waiting for your update, ty for your time JScott!!!

**Comment by JScott** [comment]
I just tried importing the scripts via [unitypackage](https://github.com/JScott/cardboard-controls/releases/tag/v3.0) and by code and they both create the prefab appropriately.

What steps did you take to import the scripts? I notice that you didn't keep the original folder structure so I'm not sure what we've done differently. If you import with the unitypackage provided by the latest release then it might go smoother.

**Comment by JScott** [comment]
It might be worth noting that copying the code directly in didn't work until I copied the official Cardboard SDK code in as well. It compiled just fine after importing both to their respective paths.

**Comment by kharysiri** [comment]
Hi!!
my bad, i doesnt download that package, i tried downloading the proyect zip and copying to my test proyect. About the path in the screenshot, i tried first time in the original path, but doesnt work, so i tried to put them outside, doesnt work too... then i made the screenshot.
Well trying via that unitypackage.. works fine!! i tried too the demoapp and works fine too...
so far i have a little problems with the magnet "click" recognize.. my phone its and Xperia Z, and the magnet sensor is in the other side of the phone, so i have to rotate 180º.. the app works... but the clicks doesnt...(in others app i have tried, the click works!) ill try to read the magnet data and figure out what is wrong...
ty for ur time JScott!

**Comment by JScott** [comment]
Glad to hear it's somewhat working now :)

I've only tested things on a Nexus 5 and with the magnetic field where I live so let me know how your testing goes. It's not easy to debug magnet data but it might help to enable some of the debug charts in the inspector for `adb logcat`. It could give you an idea of what state CC+ thinks it's in.

I'm also going to close this ticket since the prefab thing is fixed.
